package esc;

public enum TelemetryParameters {
	INPUT_MODE, RUN_MODE, ESC_STATE, PERCENT_IDLE, COMM_PERIOD, BAD_DETECTS, FET_DUTY, RPM, AMPS_AVG, AMPS_MAX, BAT_VOLTS, MOTOR_VOLTS, DISARM_CODE, CAN_NET_ID;
}